test:
	ruby rheosense.rb -p XXXX
start:
	ruby rheosense_server.rb -p XXXX
sync: 
	scp root@XXX.XXX.XXX.XX:/home/sockets/rheosense/* .
upload:
	scp * root@XXX.XXX.XXX.XX:/home/sockets/rheosense/
install:
	gem install em-websocket mongo
open: 
	ngrok http XXXX



